import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import { Button, Box } from '@mui/material';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Animal Training</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Box
        sx={{
        my: 8,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        }}> 

      <Link href="/"><h1> Animal Training </h1></Link>
      <Link href="/login">Login </Link>
      <Link href="/name">Get a Pokemon by name</Link>
      <Link href="/types">Get a Pokemon by type</Link>
      <Link href="/evolve">Get a Pokemon's next evolution stage</Link>
      <Link href="/exp">Get a Pokemon's Experience</Link>
      <Link href="/battle">Battle two Pokemon</Link>
      <Link href="/catch">Try to catch a Pokemon</Link>
      </Box>
    </div>
  )
}
